
package com.crm.webservice.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.crm.webservice.ObjectFactory;
import com.crm.webservice.VgRequest;
import com.crm.webservice.VgResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "hiboy", targetNamespace = "http://webservice.crm.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hiboy {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.crm.webservice.VgResponse
     * @throws Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendOrder", targetNamespace = "http://webservice.crm.com/", className = "com.crm.webservice.SendOrder")
    @ResponseWrapper(localName = "sendOrderResponse", targetNamespace = "http://webservice.crm.com/", className = "com.crm.webservice.SendOrderResponse")
    @Action(input = "http://webservice.crm.com/hiboy/sendOrderRequest", output = "http://webservice.crm.com/hiboy/sendOrderResponse", fault = {
        @FaultAction(className = Exception.class, value = "http://webservice.crm.com/hiboy/sendOrder/Fault/Exception")
    })
    public VgResponse sendOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        VgRequest arg0)
        throws Exception
    ;

}
