
package com.crm.webservice.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VGServiceImplService", targetNamespace = "http://Impl.webservice.crm.com/", wsdlLocation = "http://192.168.88.44:8080/pro1/VGServiceImplService?wsdl")
public class VGServiceImplService
    extends Service
{

    private final static URL VGSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VGSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName VGSERVICEIMPLSERVICE_QNAME = new QName("http://Impl.webservice.crm.com/", "VGServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.88.44:8080/pro1/VGServiceImplService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VGSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        VGSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public VGServiceImplService() {
        super(__getWsdlLocation(), VGSERVICEIMPLSERVICE_QNAME);
    }

    public VGServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VGSERVICEIMPLSERVICE_QNAME, features);
    }

    public VGServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, VGSERVICEIMPLSERVICE_QNAME);
    }

    public VGServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VGSERVICEIMPLSERVICE_QNAME, features);
    }

    public VGServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VGServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Hiboy
     */
    @WebEndpoint(name = "VGServiceImplPort")
    public Hiboy getVGServiceImplPort() {
        return super.getPort(new QName("http://Impl.webservice.crm.com/", "VGServiceImplPort"), Hiboy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Hiboy
     */
    @WebEndpoint(name = "VGServiceImplPort")
    public Hiboy getVGServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Impl.webservice.crm.com/", "VGServiceImplPort"), Hiboy.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VGSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw VGSERVICEIMPLSERVICE_EXCEPTION;
        }
        return VGSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
